/*******************************************************************************
 *
 * This file is part of the LGS1920/studio project.
 *
 * File: Widget2Canvas.js
 *
 * Author : LGS1920 Team
 * email: contact@lgs1920.fr
 *
 * Created on: 2025-11-19
 * Last modified: 2025-11-19
 *
 *
 * Copyright © 2025 LGS1920
 ******************************************************************************/

import { LGS_WIDGET_SCALE_FACTOR } from '@Core/constants'
import { snapdom }                 from '@zumer/snapdom'

/**
 * Widget2Canvas — High-performance version
 *
 * Replaces a DOM widget with a perfectly synced canvas using snapdom.
 * Only refreshes when actual DOM mutations occur, preventing redundant work.
 * Uses `queueMicrotask` to batch rapid changes into a single update.
 * Direct canvas output via `snapdom.toCanvas` for maximum speed.
 *
 * @class
 */
export class Widget2Canvas {
    /** Original widget element (hidden while the canvas is active) */
    #original = null

    /** Current visible canvas generated by snapdom */
    #canvas = null

    /** Original computed display value (flex, grid, etc.) */
    #originalDisplay = 'block'

    /** Snapdom configuration options */
    #options = {}

    /** Flag to prevent overlapping refresh cycles */
    #pendingRefresh = false

    /**
     * Creates a canvas mirror of the target element.
     *
     * @param {HTMLElement} target               Element to mirror
     * @param {Object}      [options={}]         Snapdom options
     * @param {number}      [options.scale]      Resolution scale (defaults to devicePixelRatio)
     * @param {boolean}     [options.includeBackground=true]
     * @param {boolean}     [options.includeShadowDom=true]
     */
    constructor(target, options = {}) {
        if (!target || !(target instanceof HTMLElement)) {
            return
        }

        this.#original = target
        this.#options = {
            scale:             window.devicePixelRatio || 1,
            includeBackground: true,
            includeShadowDom:  true,
            ...options,
        }

        // Capture the real display value before hiding
        this.#originalDisplay = getComputedStyle(target).display

        // Hide original immediately – prevents flash
        target.style.display = 'none'

        // High-performance observer: only trigger on real changes
        const observer = new MutationObserver((mutations) => {
            if (mutations.length === 0) {
                return
            }

            // Batch rapid mutations into a single refresh
            if (!this.#pendingRefresh) {
                this.#pendingRefresh = true
                queueMicrotask(() => {
                    this.#refresh()
                    this.#pendingRefresh = false
                })
            }
        })

        observer.observe(target, {
            childList:     true,
            subtree:       true,
            attributes:    true,
            characterData: true,
        })

        // Initial render
        this.#refresh()
    }

    /**
     * Creates a fresh off-screen clone, captures it with snapdom,
     * and replaces the current visible canvas.
     *
     * @private
     */
    #refresh() {
        if (!this.#original) {
            return
        }

        const clone = this.#original.cloneNode(true)
        clone.classList.add('lgs-widget-clone')
        clone.style.display = this.#originalDisplay
        clone.style.visibility = 'visible'

        document.body.appendChild(clone)

        // Direct canvas capture – fastest path
        snapdom.toCanvas(clone, this.#options)
            .then(snap => {
                // Scale the canvas
                const scaledCanvas = document.createElement('canvas')
                const scaledWidth = Math.round(snap.width / LGS_WIDGET_SCALE_FACTOR)
                const scaledHeight = Math.round(snap.height / LGS_WIDGET_SCALE_FACTOR)

                scaledCanvas.width = scaledWidth
                scaledCanvas.height = scaledHeight

                const ctx = scaledCanvas.getContext('2d')
                ctx.drawImage(snap, 0, 0, scaledWidth, scaledHeight)

                // Apply the same class as before
                scaledCanvas.classList.add('lgs-widget-canvas')

                // Replace the old canvas (or insert the first one)
                if (this.#canvas) {
                    this.#canvas.replaceWith(scaledCanvas)
                }
                else {
                    this.#original.parentNode.insertBefore(scaledCanvas, this.#original)
                }

                this.#canvas = scaledCanvas
            })
            .catch(() => {
                // Silent fallback – UI stays stable
            })
            .finally(() => {
                clone.remove()
            })
    }

    /** Returns the 2D rendering context (useful for drawing on top) */
    getContext() {
        return this.#canvas?.getContext('2d') ?? null
    }

    /** Returns the visible canvas element */
    getCanvas() {
        return this.#canvas
    }

    /** Shows the canvas overlay */
    show() {
        if (this.#canvas) {
            this.#canvas.style.opacity = '1'
        }
    }

    /** Hides the canvas overlay */
    hide() {
        if (this.#canvas) {
            this.#canvas.style.opacity = '0'
        }
    }

    /** Shows the original DOM widget and hides the canvas */
    showOriginal() {
        if (this.#canvas) {
            this.#canvas.style.display = 'none'
        }
        if (this.#original) {
            this.#original.style.display = this.#originalDisplay
        }
    }

    /** Hides the original widget (default mirrored state) */
    hideOriginal() {
        if (this.#canvas) {
            this.#canvas.style.display = 'block'
        }
        if (this.#original) {
            this.#original.style.display = 'none'
        }
    }

    /** Cleans up resources and restores the original element */
    destroy() {
        this.#canvas?.remove()
        if (this.#original) {
            this.#original.style.display = this.#originalDisplay
        }
        this.#canvas = null
        this.#original = null
    }
}